#!/bin/bash
#
# Starts or stops firewalld logging of dropped/rejected packets.
#
RULES_AFTER=${RULES_AFTER:-"2"}
LOG_PREFIX=${LOG_PREFIX:-"FIREWALLED: "}
LOG_LIMIT=${LOG_LIMIT:-"1/min"}
LOG_BURST=${LOG_BURST:"10"}
#
# See how are we called
#
case $(basename $0) in
*start)
	# Insert the LOG just before the last $RULES_AFTER rules of firewalld.
	RULE_NUMBER=$(( $(/usr/sbin/iptables -n -L INPUT  | /usr/bin/wc -l) - ${RULES_AFTER} - 1  ))
	COMMAND="-I"
	;;
*stop)
	# Delete the rule
	RULE_NUMBER=""
	COMMAND="-D"
	;;
*)
	echo -e "This script should be called as firewalld-logging-start or firewalld-logging-stop with a symbolic link:

\t\$ ln -siv $(basename $0) $(basename $0)-stop; ln -siv $(basename $0) $(basename $0)-start.
"
	exit 1
	;;
esac

/usr/sbin/iptables ${COMMAND} INPUT ${RULE_NUMBER} -j LOG \
    --log-prefix=${LOG_PREFIX} \
    -m limit --limit=1/min --limit-burst=10
